language: csharp
solution: ./src/BOG.DropZone.sln
os:
- linux
mono: none
dotnet: 6.0.201
script:
- chmod +x ./deploy.sh 
- ./deploy.sh

# safelist
branches:
  only:
  - master
  - release
  - develop
