language: csharp
solution: ./src/BOG.DropZone.sln
mono: none
dotnet: 3.1
install:
script:
- dotnet build ./src/BOG.DropZone.sln
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master
