language: csharp
solution: ./src/BOG.DropZone.sln
mono: none
dotnet: 3.1
stages:
  - name: compile
    script:
      - dotnet build -c $BUILD_CONFIG ./src/BOG.DropZone.sln
      if: branch = master
        script:
        - dotnet nuget push ./src/BOG.DropZone.Common/bin/Release/BOG.DropZone.Common.*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE --skip-duplicate
        - dotnet nuget push ./src/BOG.DropZone.Client/bin/Release/BOG.DropZone.Client.*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE --skip-duplicate
