language: csharp
solution: ./src/BOG.DropZone.sln
mono: none
dotnet: 3.1
stages:
  - name: compileMaster
    if: branch = master
      script:
        - dotnet build -c $BUILD_CONFIG ./src/BOG.DropZone.sln
        - dotnet nuget push ./src/BOG.DropZone.Common/bin/Release/BOG.DropZone.Common.*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE --skip-duplicate
        - dotnet nuget push ./src/BOG.DropZone.Client/bin/Release/BOG.DropZone.Client.*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE --skip-duplicate
  - name: compileRelease
    if: branch = release
      script:
        - dotnet build -c $BUILD_CONFIG ./src/BOG.DropZone.sln
  - name: compileDevelop
    if: branch = develop
      script:
        - dotnet build -c $BUILD_CONFIG ./src/BOG.DropZone.sln
