language: csharp
solution: ./src/BOG.DropZone.sln
mono: none
dotnet: 3.1
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
script:
- dotnet build ./src/BOG.DropZone.sln
- mono nuget.exe setApiKey $NUGET_API_KEY -Source $NUGET_SOURCE -Verbosity quiet
- mono nuget push ./src/BOG.DropZone.Client/bin/Release/BOG.DropZone.Common.*.nupkg -Source $Source
- mono nuget push ./src/BOG.DropZone.Client/bin/Release/BOG.DropZone.Client.*.nupkg -Source $Source

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master
